In [1]:
import numpy as np

In [21]:
C = np.array([np.arange(2,10,2), np.arange(3,15,3), np.arange(7,35,7)] )
C

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 7, 14, 21, 28]])

In [15]:
x = np.arange(2,10,2)
x

array([2, 4, 6, 8])

In [18]:
y = np.arange(3,15,3)
y

array([ 3,  6,  9, 12])

In [19]:
z = np.arange(7,35,7)
z

array([ 7, 14, 21, 28])